TWITTER_CONSUMER_KEY: "liGy3aZJQjziefEq7jOTGFNKG"
TWITTER_CONSUMER_SECRET: "7Y62wd2lrjGkFsxe5pZjwfCokOZyf6ek5hxzvy16YfEcOkGnci"
TWITTER_ACCESS_TOKEN: "205796907-xhY3LSRxac1WEF9n01OUpMJFI5Q7nQYTuhCQlTNO"
TWITTER_ACCESS_TOKEN_SECRET: "dKmJPptdT7XfyUbUheMeIR9TWXpUO9SWqLQnGpzg9X2dU"
BITLY_ACCESS_TOKEN: "6e4fa4018ad337d08701c3a5cb489b6e1ca40019"
GIPHY_API_KEY_PUBLIC: "dc6zaTOxFJmzC"